# Generated by Django 5.1.6 on 2025-02-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('chaos_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('chaos_points', models.IntegerField()),
                ('employee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions1', to='chaos_tracker.employee')),
                ('employee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions2', to='chaos_tracker.employee')),
            ],
        ),
    ]
